### ISSUE TITLE
Drain cleaner pod crashlooping  with "no such file or directory" error

### ISSUE THREAD

**Issue by OuesFa** [strimzi/drain-cleaner#80]
When trying to deploy the drain-cleaner Helm chart (version 0.4.2), I encounter the following error:

```
k describe po strimzi-drain-cleaner-78f4976f98-f8wfs 
[...]
Message: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/application": stat /application: no such file or directory: unknown
[...]
```

Here is the YAML configuration I'm using to deploy:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-drain-cleaner
  namespace: dbre
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://strimzi.io/charts/
      chart: strimzi-drain-cleaner
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: strimzi-drain-cleaner
  values:
    registry: "my-registry"
    spec:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi-drain-cleaner
  namespace: dbre
spec:
  url: https://strimzi.io/charts/
  interval: 1m
```

What am I missing here please?
